# noinspection PyStatementEffect
{
    'name': 'Agrista Material Theme',
    'summary': 'Material themes for the website frontend',
    'description': 'This theme module provides material design components for the website frontend.',
    'category': 'Theme',
    'sequence': 900,
    'version': '1.0',
    'depends': ['website'],
    'data': [
        'views/theme.xml',
        'views/options.xml',
        'views/templates.xml',
        'views/snippets.xml',
        'views/snippets/header_carousel.xml',
        'views/snippets/header_page.xml',
        'views/snippets/block_img_txt.xml',
        'views/snippets/block_txt_img.xml',
        'views/snippets/block_customer_ribbon.xml',
        'views/snippets/block_teamviewer.xml',
        'views/snippets/block_how_it_works.xml',
        'views/snippets/featured_row.xml',
        'views/snippets/featured_list.xml',
        'views/snippets/plans_farmer.xml',
        'views/snippets/block_faq.xml',
    ],
    'images': ['static/description/material.png'],
    'application': False,
}
