# noinspection PyStatementEffect
{
    'name': 'Agrista Material Theme',
    'summary': 'Material themes for the website frontend',
    'description': 'This theme module provides material design components for the website frontend.',
    'category': 'Theme',
    'version': '1.0',
    'depends': ['website', 'website_blog', ],
    'data': [
        'views/theme.xml',
        'views/options.xml',
        'views/templates.xml',
        'views/snippets.xml',
        'views/snippets/header_carousel.xml',
        'views/snippets/header_landing.xml',
        'views/snippets/header_page.xml',
        'views/snippets/header_landing.xml',
        'views/snippets/img_txt.xml',
        'views/snippets/txt_img.xml',
        'views/snippets/customer_ribbon.xml',
        'views/snippets/teamviewer.xml',
        'views/snippets/how_it_works.xml',
        'views/snippets/featured_row.xml',
        'views/snippets/featured_list.xml',
        'views/snippets/references.xml',
        'views/snippets/quotes_slider.xml',
        'views/snippets/plans_farmer.xml',
        'views/snippets/faq.xml',
    ],
    'images': ['static/description/material.png'],
}
